name: Pull Request Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - uses: actions/setup-node@v2.1.5
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        registry-url: 'https://npm.pkg.github.com'
        scope: '@melscoop'

    - uses: actions/cache@v2.1.4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}

